### ISSUE TITLE
i built it and works but i have issue and errors

### ISSUE THREAD

**Issue by spix18** [Macsimka/Albion-radar#1]
```c#
HandleHarvestableChangeState: System.InvalidCastException: Unable to cast object of type 'System.Byte[]' to type 'System.IConvertible'.
   at System.Convert.ToByte(Object value)
   at Holo.Networking.PacketHandler.HandleHarvestableChangeState(Dictionary`2 parameters) in C:\Users\Administrator\Desktop\Albion-radar-master\Holo\Networking\PacketHandler.cs:line 290
HandleHarvestableChangeState: System.InvalidCastException: Unable to cast object of type 'System.Byte[]' to type 'System.IConvertible'.
   at System.Convert.ToByte(Object value)
   at Holo.Networking.PacketHandler.HandleHarvestableChangeState(Dictionary`2 parameters) in C:\Users\Administrator\Desktop\Albion-radar-master\Holo\Networking\PacketHandler.cs:line 290
HandleNewHarvestableObject: System.InvalidCastException: Unable to cast object of type 'System.Int16[]' to type 'System.IConvertible'.
   at System.Convert.ToInt32(Object value)
   at Holo.Networking.PacketHandler.HandleNewHarvestableObject(Dictionary`2 parameters) in C:\Users\Administrator\Desktop\Albion-radar-master\Holo\Networking\PacketHandler.cs:line 251


``` 

i installed winpcap4.1.3 but still same issue ? any idea how to fix this ?

**Comment by Macsimka** [comment]
It's normal, because of last game update. Ping me tomorrow, I'll fix.

**Comment by Macsimka** [comment]
@spix18 try.

**Comment by spix18** [comment]
> @spix18 try.

works perfectly, thank you

**Comment by spix18** [comment]
i have this error on mist tho 
![image](https://github.com/Macsimka/Albion-radar/assets/7613901/ecca8bee-3a51-4964-84db-ca82901c57bf)

i could see the enemies in towns but in mists i only hear the sound but no red dot on mini map
i will keep testing

**Comment by spix18** [comment]
i could see the enemies in towns but in mists i only hear the sound but no red dot on mini map

**Comment by ZeroHalfy** [comment]
can u update? its error. and in the mist cant see red dot (enemy)

**Comment by Macsimka** [comment]
Try last release, or compile with last commit.
If windows defender complains, that's normal. Microsoft hates dot net applications built with Visual Studio 2019-2022 :D

**Comment by spix18** [comment]
> Try last release, or compile with last commit. If windows defender complains, that's normal. Microsoft hates dot net applications built with Visual Studio 2019-2022 :D

everything works, thank you for the update but would you please add a template to add mobs detection, i want to help add bosses and mini bosses and others mobs, i really like this radar its has a really good friendly overlay, but i miss other features from others radars :(
