### ISSUE TITLE
Problem with start

### ISSUE THREAD

**Issue by mszota** [Macsimka/Albion-radar#4]
Hi man,

i have a problem with your program.
im used microsoft visual studio, but at first, when i trying to start holo, then i have a first error like: Desktop\Albion-radar-master\Holo\bin\Debug HOLO.EXE doesn't exist. 

i need start the holo like a debug or release?

the second one: 

Severity Code Description Project File Line Bypass status
Error (active) NU1101 Cannot find package System.Data.DataSetExtensions. There are no packages with this ID in the sources: Microsoft Visual Studio Offline Packages, Package source Holo C:\Users\\Desktop\Albion-radar-master\Holo\Holo.csproj 1
Error (Active) NU1101 The Microsoft.NETCore.Platforms package could not be found. There are no packages with this ID in the sources: Microsoft Visual Studio Offline Packages, Package source Overlay.NET C:\Users\\Desktop\Albion-radar-master\Overlay.NET\Overlay.NET.csproj 1
Error (active) NU1101 Package Costura.Fody could not be found. There are no packages with this ID in the sources: Microsoft Visual Studio Offline Packages, Package source Holo C:\Users\\Desktop\Albion-radar-master\Holo\Holo.csproj 1
Error (active) NU1101 PacketDotNet could not be found. There are no packages with this ID in the sources: Microsoft Visual Studio Offline Packages, Package source Holo C:\Users\\Desktop\Albion-radar-master\Holo\Holo.csproj 1
Error (active) NU1101 The System.Memory package could not be found. There are no packages with this ID in the sources: Microsoft Visual Studio Offline Packages, Package source Holo C:\Users\\Desktop\Albion-radar-master\Holo\Holo.csproj 1
Error (active) NU1101 Cannot find package System.Text.Encoding.CodePages. There are no packages with this ID in the sources: Microsoft Visual Studio Offline Packages, Package source Holo C:\Users\\Desktop\Albion-radar-master\Holo\Holo.csproj 1
Error (Active) NU1101 Cannot find package Microsoft.Extensions.Logging.Abstractions. There are no packages with this ID in the sources: Microsoft Visual Studio Offline Packages, Package source Holo C:\Users\\Desktop\Albion-radar-master\Holo\Holo.csproj 1
Error (Active) NU1101 The Microsoft.NETCore.Platforms package could not be found. There are no packages with this ID in the sources: Microsoft Visual Studio Offline Packages, Package source Holo C:\Users\\Desktop\Albion-radar-master\Holo\Holo.csproj 1
Warning (Active) NU1603 SharpDX 4.2.0 depends on NETStandard.Library (>= 1.6.1), but NETStandard.Library 1.6.1 was not found. The best approximate match recognized is NETStandard.Library 2.0.3. Overlay.NET C:\Users\\Desktop\Albion-radar-master\Overlay.NET\Overlay.NET.csproj 1
Warning (Active) NU1603 SharpDX.Direct2D1 4.2.0 depends on NETStandard.Library (>= 1.6.1), but NETStandard.Library 1.6.1 was not found. The best approximate match recognized is NETStandard.Library 2.0.3. Overlay.NET C:\Users\\Desktop\Albion-radar-master\Overlay.NET\Overlay.NET.csproj 1
Warning (Active) NU1603 SharpDX.DXGI 4.2.0 depends on NETStandard.Library (>= 1.6.1), but NETStandard.Library 1.6.1 was not found. The best approximate match recognized is NETStandard.Library 2.0.3. Overlay.NET C:\Users\\Desktop\Albion-radar-master\Overlay.NET\Overlay.NET.csproj 1
Warning (Active) NU1603 SharpDX.Mathematics 4.2.0 depends on NETStandard.Library (>= 1.6.1), but NETStandard.Library 1.6.1 was not found. The best approximate match recognized is NETStandard.Library 2.0.3. Overlay.NET C:\Users\\Desktop\Albion-radar-master\Overlay.NET\Overlay.NET.csproj 1
Warning (Active) NU1603 SharpDX 4.2.0 depends on NETStandard.Library (>= 1.6.1), but NETStandard.Library 1.6.1 was not found. The best approximate match recognized is NETStandard.Library 2.0.3. Holo C:\Users\\Desktop\Albion-radar-master\Holo\Holo.csproj 1
Warning (Active) NU1603 SharpDX.Direct2D1 4.2.0 depends on NETStandard.Library (>= 1.6.1), but NETStandard.Library 1.6.1 was not found. The best approximate match recognized is NETStandard.Library 2.0.3. Holo C:\Users\\Desktop\Albion-radar-master\Holo\Holo.csproj 1
Warning (Active) NU1603 SharpDX.DXGI 4.2.0 depends on NETStandard.Library (>= 1.6.1), but NETStandard.Library 1.6.1 was not found. The best approximate match recognized is NETStandard.Library 2.0.3. Holo C:\Users\\Desktop\Albion-radar-master\Holo\Holo.csproj 1
Warning (Active) NU1603 SharpDX.Mathematics 4.2.0 depends on NETStandard.Library (>= 1.6.1), but NETStandard.Library 1.6.1 was not found. The best approximate match recognized is NETStandard.Library 2.0.3. Holo C:\Users\\Desktop\Albion-radar-master\Holo\Holo.csproj 1

**Comment by Macsimka** [comment]
https://github.com/Macsimka/Albion-radar/releases/tag/1.0

**Comment by mszota** [comment]
lol man thats work :D great job thanks 👍
